### ISSUE TITLE
support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [SIRprise/SSD-LED#13]
it requires NET 4.5 so it actually doesn't support Windows XP.
hope you fix this for users who don't like W10/W11 and similar shit

**Comment by SIRprise** [comment]
The requirement for .NET 4.5 is a new one. You could try a previous version, maybe from 2020 (requires .NET 4.0)

**Comment by andika207** [comment]
my bad. you are right.
I normally try older releases but this time I simply forgot to do so. (the version 1.06 is ok for WinXP)
I don't like the tray-bar icon quality because it looks overpixelated
I am writting right from an HDD so I am not sure why the red 'led' is blinking on the SSD's partition
the default red color is attributed to ''write'' only but I am writting nothing on the SSD side.

**Comment by andika207** [comment]
I once tried a similar utility for HDD's
the result was not good because the tray icon was unable to match the PC case led. (at least not all the time)
hope I am wrong but I feel this SSD-LED won't work as expected.

**Comment by SIRprise** [comment]
I just tested 1.0.6 with XP, too: it works as it should. For simulating HDD activity I used a HDD benchmark tool.
Sorry for the simply icon, but I'm not an artist. There are more issues open relating to the icon style...
To be sure the red blinking on your PC is from the SSD, please use the "single drive monitor" checkbox. I guess the red blinking is from another drive, but I won't be able to analyse it because the measurement itself is done by windows, not from the tool.
The non-matching LED was new to me, but I also saw it as I just tested it with an old laptop. I guess it has to do with caching stuff. Be aware that there are also settings for the "reaction time" ("refresh interval") in which all activity is summed up and a matching color brightness is calculated and there is the maximum speed - also for calculating. Maybe it matches better if you play with these settings (and maybe deactivate caching for testing purposes). I guess in default setting, the LED blinking is 100ms delayed by setting (because of the integrating/sum up) and maybe additional ~10ms because windows has no hard realtime with 1ms.
Edit: I just tested again with setting 50KB/s and 50ms and it was very synchronous.
