### ISSUE TITLE
Installation refusal

### ISSUE THREAD

**Issue by 411621** [SIRprise/SSD-LED#15]
Does not install on Windows 10 22H2 19045.2311

Upon initiating set up a small window pops up "launching application" showing a symbolic desktop and a globe. (1) 
Apparently tries to connect outbound yet my interactive monitor (ESET) does not report any such attempt. 
Below it says (1) **"Verifying application requirements.  This may take a few moments."**

Then a strange application install security warning --never seen before or with any other app.-- message is: 
**"Your administrator has blocked this application because it potentially poses a security risk to your computer"**

I am the admin and run everything in admin mode. There's no such thing that I blocked this app! Any other application installation does not trigger such a message.

Then it shows the name of the app, location from and publisher "unknown publisher". (2)

At the bottom it says  **"your security settings do not allow this application to be installed on your computer"**(2)

Of all the applications I have installed, tried and tested none ever produced this.
What's going on here?

My system is up to date and from all the apps in the world, none ever has done that!

(1)
![Clipboard-3](https://user-images.githubusercontent.com/29167457/204588425-34c6694e-c0ce-4bc2-a71f-0aa58daddfed.jpg)

(2)
![Clipboard-2](https://user-images.githubusercontent.com/29167457/204588532-08d77e6e-3db7-4a3d-9ccf-37b8b64e8bc5.jpg)

**Comment by SIRprise** [comment]
Ah, thanks for pointing that out!
I also didn't see that with my app... but I remember a similar case with an app at work... Please try to change that registry key shown here:
https://www.reddit.com/r/techsupport/comments/72fnmg/cant_install_program_on_windows_10_your_security/
I guess the installer tries to download missing components (or simply check it?) - that only could be .NET4.5, I'm wondering it sees MS as a site it have not enough trust for, but I guess it uses http instead of https - methods that create warnings nowadays.

Edit:
If that doesn't work, you could use the 1.0.6 version, which requires .NET 4.0 only and you also could bypass the installer by downloading the exe-file and use it like a portable-version.

**Comment by SIRprise** [comment]
The idea is to renew/replace the installer.
